### ISSUE TITLE
TypeError: cannot pickle 'isaacgym._bindings.linux-x86_64.gym_38.Gym' object

### ISSUE THREAD

**Issue by 13253591602** [AI4Finance-Foundation/ElegantRL#221]
When I run examples/demo_Isaac_Gym.py. The following error has occurred:

Traceback (most recent call last):
  File "examples/demo_Isaac_Gym2.py", line 81, in <module>
    demo(task)
  File "examples/demo_Isaac_Gym2.py", line 76, in demo
    train_and_evaluate(args)
  File "/home/yh/py-packages/ElegantRL/elegantrl/train/run.py", line 89, in train_and_evaluate
    evaluator = init_evaluator(args, gpu_id)
  File "/home/yh/py-packages/ElegantRL/elegantrl/train/run.py", line 68, in init_evaluator
    eval_env = build_env(args.env, eval_func, eval_args)
  File "/home/yh/py-packages/ElegantRL/elegantrl/train/config.py", line 208, in build_env
    env = deepcopy(env)
  File "/home/yh/anaconda3/envs/erl/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/yh/anaconda3/envs/erl/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/yh/anaconda3/envs/erl/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/yh/anaconda3/envs/erl/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/yh/anaconda3/envs/erl/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/yh/anaconda3/envs/erl/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/yh/anaconda3/envs/erl/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/yh/anaconda3/envs/erl/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/yh/anaconda3/envs/erl/lib/python3.8/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'isaacgym._bindings.linux-x86_64.gym_38.Gym' object

I use Isaac Gym - Preview 4 Release.

**Comment by Yonv1943** [comment]
In addition: 
- This bug don't occur in DGX64 server(A100 GPU), 3080GPU or 3090GPU.
- `check_isaac_gym()`  can be run normally. https://github.com/AI4Finance-Foundation/ElegantRL/blob/5cf6190d114374b975232f37fcdbae6e10f6e22e/elegantrl/envs/IsaacGym.py#L213
- This bug occurs in Isaac Gym - Preview 4 or Preview 3
- This bug occurs in Isaac Gym - Preview 4 or Preview 3

**Comment by 13253591602** [comment]
> In addition:
> 
> * This bug don't occur in DGX64 server(A100 GPU), 3080GPU or 3090GPU.
> * `check_isaac_gym()`  can be run normally. https://github.com/AI4Finance-Foundation/ElegantRL/blob/5cf6190d114374b975232f37fcdbae6e10f6e22e/elegantrl/envs/IsaacGym.py#L213
> * This bug occurs in Isaac Gym - Preview 4 or Preview 3
> * This bug occurs in Isaac Gym - Preview 4 or Preview 3


yeah, this function works well on my server

**Comment by Timkeeper2018** [comment]
" RTX3080ti ,  Isaac Gym - Preview 4 " got this error too.

**Comment by mikygit** [comment]
Is there a workaround a part from downgrading IsaacGym?

**Comment by Skylark0924** [comment]
" RTX3090 , Isaac Gym - Preview 4 " got this error too.
