### ISSUE TITLE
AgentMATD3 cannot be call by train_agent_multiprocessing

### ISSUE THREAD

**Issue by niceban** [AI4Finance-Foundation/ElegantRL#281]
When I call AgentMATD3 through train_agent_multiprocessing, the following error occurs: ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'module' object
(I add AgentMATD3 to demo_DDPG_TD3_SAC.py)

the log is like
```
/opt/anaconda3/envs/erl/bin/python ~/Downloads/ElegantRL-master/examples/demo_DDPG_TD3_SAC.py
env_args = {'env_name': 'Pendulum-v1',
            'num_envs': 1,
            'max_step': 200,
            'state_dim': 3,
            'action_dim': 1,
            'if_discrete': False}
| Arguments Remove cwd: ./Pendulum_ntrl.agents.AgentMATD3_0
Traceback (most recent call last):
  File "/Users/c/Downloads/ElegantRL-master/examples/demo_DDPG_TD3_SAC.py", line 238, in <module>
    train_ddpg_td3_sac_for_pendulum()
  File "/Users/c/Downloads/ElegantRL-master/examples/demo_DDPG_TD3_SAC.py", line 43, in train_ddpg_td3_sac_for_pendulum
    train_agent_multiprocessing(args)  # train_agent(args)
  File "/Users/c/Downloads/ElegantRL-master/elegantrl/train/run.py", line 124, in train_agent_multiprocessing
    [process.start() for process in process_list]
  File "/Users/c/Downloads/ElegantRL-master/elegantrl/train/run.py", line 124, in <listcomp>
    [process.start() for process in process_list]
  File "/opt/anaconda3/envs/erl/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/anaconda3/envs/erl/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/opt/anaconda3/envs/erl/lib/python3.9/multiprocessing/context.py", line 291, in _Popen
    return Popen(process_obj)
  File "/opt/anaconda3/envs/erl/lib/python3.9/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
  File "/opt/anaconda3/envs/erl/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/anaconda3/envs/erl/lib/python3.9/multiprocessing/popen_forkserver.py", line 47, in _launch
    reduction.dump(process_obj, buf)
  File "/opt/anaconda3/envs/erl/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'module' object
```

**Comment by niceban** [comment]
Opened a new issue
