### ISSUE TITLE
None of the IsaacGym related examples work

### ISSUE THREAD

**Issue by hskalin** [AI4Finance-Foundation/ElegantRL#322]
running the following demo 
```
python examples/demo_Isaac_Gym.py
```
throws up the error
```
Traceback (most recent call last):
  File "examples/demo_Isaac_Gym.py", line 6, in <module>
    from elegantrl.train.run import train_and_evaluate
ImportError: cannot import name 'train_and_evaluate' from 'elegantrl.train.run' 
```
Also the [tutorial code](https://elegantrl.readthedocs.io/en/latest/tutorial/isaacgym.html) throws the following error:
```
Traceback (most recent call last):
  File "mytest.py", line 3, in <module>
    from elegantrl.envs.IsaacGym import IsaacVecEnv, IsaacOneEnv
  File "/home/nilaksh/rl/ElegantRL/elegantrl/envs/IsaacGym.py", line 5, in <module>
    from elegantrl.envs.isaac_tasks import isaacgym_task_map
ModuleNotFoundError: No module named 'elegantrl.envs.isaac_tasks'
```

Hence I request you to please solve these issues. I'm using the latest version of ERL

**Comment by CRHPlusAI** [comment]
Facing the same problem. Is there any update? Thanks!

**Comment by HiFei4869** [comment]
Same problem... Do you have any solution?
