### ISSUE TITLE
none of your example works...

### ISSUE THREAD

**Issue by softd1sk** [AI4Finance-Foundation/ElegantRL#326]
Traceback (most recent call last):
  File "C:\***\marco\Desktop\Stock_invester\model_trainer.py", line 14, in <module>
    from finrl.agents.elegantrl.models import DRLAgent as DRLAgent_erl
  File "C:\Users\***\AppData\Local\miniconda3\envs\Stock_invester\lib\site-packages\finrl\agents\elegantrl\models.py", line 11, in <module>
    from elegantrl.train.config import Arguments
ImportError: cannot import name 'Arguments' from 'elegantrl.train.config' (C:\Users\***\AppData\Local\miniconda3\envs\Stock_invester\lib\site-packages\elegantrl\train\config.py)

**Comment by Yonv1943** [comment]
ImportError: cannot import name 'Arguments' from 'elegantrl.train.config'

Change `Arguments` to `Config` can fix this error.

```
form elegantrl.train.config import Arguments
args = Arguemtns(...)
```
↓
```
form elegantrl.train.config import Config
args = Config(...)
```
