### ISSUE TITLE
ReplayBuffer Error When gpu can't use

### ISSUE THREAD

**Issue by CarlDegio** [AI4Finance-Foundation/ElegantRL#36]
In run.py, line 140.
If I set `if_gpu` False, the training process error because some variable is np.ndarray. But neural network needs tensor.

Running demo.py, demo2_continuous_action_space_off_policy() and set replaybuffer if_gpu False could show this problems. Error happens:

```
Traceback (most recent call last):
  File "ElegantRL/elegantrl/demo.py", line 413, in <module>
    demo2_continuous_action_space_off_policy()


  File "ElegantRL/elegantrl/demo.py", line 73, in demo2_continuous_action_space_off_policy
    train_and_evaluate(args)


  File "ElegantRL/elegantrl/run.py", line 153, in train_and_evaluate
    agent.update_net(buffer, target_step, batch_size, repeat_times)  # pre-training and hard update


  File "ElegantRL/elegantrl/agent.py", line 562, in update_net
    obj_critic, state = self.get_obj_critic(buffer, batch_size, alpha)


  File "ElegantRL/elegantrl/agent.py", line 508, in get_obj_critic_raw
    next_a, next_logprob = self.act.get_action_logprob(next_s)


  File "ElegantRL/elegantrl/net.py", line 211, in get_action_logprob
    t_tmp = self.net_state(state)


  File "anaconda3/envs/py3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)


  File "anaconda3/envs/py3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)


  File "anaconda3/envs/py3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)


  File "anaconda3/envs/py3/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 96, in forward
    return F.linear(input, self.weight, self.bias)


  File "anaconda3/envs/py3/lib/python3.8/site-packages/torch/nn/functional.py", line 1847, in linear
    return torch._C._nn.linear(input, weight, bias)


TypeError: linear(): argument 'input' (position 1) must be Tensor, not numpy.ndarray
```

Some lines number may have bias because I change some code.

**Comment by zhengsizuo** [comment]
You should transform the ndarray to torch tensor, or just keep if_gpu **True**.

**Comment by Yonv1943** [comment]
We have fully upgraded ElegantRL and now supports multiple GPU training (1~8 GPU). 

**Now the problem you mentioned has been resolved**. I'm sorry that we have been busy developing the 80 GPU version (Cloud platform) of ElegantRL, and we were unable to reply to you in time.

I will close this question in 3 days.
