### ISSUE TITLE
RuntimeError: mat1 dim 1 must match mat2 dim 0

### ISSUE THREAD

**Issue by liuqi8827** [AI4Finance-Foundation/ElegantRL#46]
Thanks for your work.

I am facing a problem when I run demo.py (demo_discrete_action_off_policy())
I set `if_train_cart_pole = 1,  if_train_lunar_lander = 0` and `if_train_cart_pole = 0,  if_train_lunar_lander = 1`
I got the same error:

```
Traceback (most recent call last):
  File "/home/lq/ElegantRL/elegantrl/demo.py", line 154, in <module>
    demo_discrete_action_off_policy()
  File "/home/lq/ElegantRL/elegantrl/demo.py", line 126, in demo_discrete_action_off_policy
    train_and_evaluate(args)
  File "/home/lq/ElegantRL/elegantrl/run.py", line 177, in train_and_evaluate
    array_tuple = agent.explore_env(env, target_step)
  File "/home/lq/ElegantRL/elegantrl/agent.py", line 215, in explore_env
    action = self.select_action(state)  # assert isinstance(action, int)
  File "/home/lq/ElegantRL/elegantrl/agent.py", line 271, in select_action
    actions = self.act(states)
  File "/home/lq/anaconda3/envs/py3.6-elegantrl/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lq/ElegantRL/elegantrl/net.py", line 50, in forward
    tmp = self.net_state(state)
  File "/home/lq/anaconda3/envs/py3.6-elegantrl/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lq/anaconda3/envs/py3.6-elegantrl/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/lq/anaconda3/envs/py3.6-elegantrl/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lq/anaconda3/envs/py3.6-elegantrl/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/lq/anaconda3/envs/py3.6-elegantrl/lib/python3.6/site-packages/torch/nn/functional.py", line 1692, in linear
    output = input.matmul(weight.t())
RuntimeError: mat1 dim 1 must match mat2 dim 0
```

**Comment by Yonv1943** [comment]
We have fully upgraded ElegantRL and now supports multiple GPU training (1~8 GPU). 

**Now the problem you mentioned has been resolved**. I'm sorry that we have been busy developing the 80 GPU version (Cloud platform) of ElegantRL, and we were unable to reply to you in time.

I will close this question in three days.

**Comment by liuqi8827** [comment]
@Yonv1943 
I git clone the lastest code. I did not modify any code.
However,  when I run demo.py (demo_discrete_action_off_policy())
I got the error:

```
/home/lq/anaconda3/envs/py3.6-elegantrl/bin/python /home/lq/ElegantRL/elegantrl/demo.py
| Remove cwd: ./AgentDoubleDQN_LunarLander-v2_0
################################################################################
ID     Step    maxR |    avgR   stdR   avgS  stdS |    expR   objC   etc.
Traceback (most recent call last):
  File "/home/lq/ElegantRL/elegantrl/demo.py", line 198, in <module>
    demo_discrete_action_off_policy()
  File "/home/lq/ElegantRL/elegantrl/demo.py", line 129, in demo_discrete_action_off_policy
    train_and_evaluate(args)
  File "/home/lq/ElegantRL/elegantrl/run.py", line 197, in train_and_evaluate
    trajectory = agent.explore_env(env, target_step)
  File "/home/lq/ElegantRL/elegantrl/agent.py", line 232, in explore_one_env
    action = self.select_actions((state,))[0]  # assert isinstance(action, int)
  File "/home/lq/ElegantRL/elegantrl/agent.py", line 317, in select_actions
    a_ints = action.argmax(dim=1).detach().cpu().numpy()
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```

**Comment by Yonv1943** [comment]
Thanks. I had fixed this bug in `Agent.py` in line 313:

            action = actions[0]
            a_ints = action.argmax(dim=1).detach().cpu().numpy()
            # ↓
            a_ints = actions.argmax(dim=1).detach().cpu().numpy()
