### ISSUE TITLE
TypeError: 'AgentPPO' object is not callable

### ISSUE THREAD

**Issue by echoyes** [AI4Finance-Foundation/ElegantRL#66]
Traceback (most recent call last):
  File "/Users/ElegantRL/elegantrl/envs/FinRL/FinRL.py", line 527, in <module>
    check_stock_trading_env()
  File "/Users/ElegantRL/elegantrl/envs/FinRL/FinRL.py", line 276, in check_stock_trading_env
    env.draw_cumulative_return(args, torch)
  File "/Users//ElegantRL/elegantrl/envs/FinRL/FinRL.py", line 213, in draw_cumulative_return
    agent = agent_rl(net_dim, state_dim, action_dim)  # build AgentRL
TypeError: 'AgentPPO' object is not callable

I'm wondering if this project maintenance has been abandoned, there are so many errors

**Comment by XiaoYangLiu-FinRL** [comment]
The opposite. We are actively changing it, thus so many errors.

**Comment by XiaoYangLiu-FinRL** [comment]
I believe this issue is fixed.
