### ISSUE TITLE
Can't run tutorial_LunarLanderContinuous-v2.py

### ISSUE THREAD

**Issue by hmomin** [AI4Finance-Foundation/ElegantRL#99]
When trying to run `tutorial_LunarLanderContinuous-v2.py`, I receive the following output, then error...

output:
```
env_args = {
    'env_num': 1,
    'env_name': 'LunarLanderContinuous-v2',
    'max_step': 1000,
    'state_dim': 8,
    'action_dim': 2,
    'if_discrete': False,
    'target_return': 200,
}
| Arguments Remove cwd: ./LunarLanderContinuous-v2_00_SAC_(-1,)
################################################################################
ID     Step    maxR |    avgR   stdR   avgS  stdS |    expR   objC   etc.
```
error:
```
Traceback (most recent call last):
  File "tutorial_LunarLanderContinous-v2.py", line 39, in <module>
    train_and_evaluate(args)
  File "/home/momin/Documents/GitHub/ElegantRL/elegantrl/train/run.py", line 21, in train_and_evaluate
    buffer, update_buffer = init_replay_buffer(args, learner_gpu, agent, env=env)
  File "/home/momin/Documents/GitHub/ElegantRL/elegantrl/train/utils.py", line 82, in init_replay_buffer
    update_buffer(agent.explore_env(env, args.target_step))
  File "/home/momin/Documents/GitHub/ElegantRL/elegantrl/train/utils.py", line 72, in update_buffer
    buffer.extend_buffer(ten_state, ten_other)
  File "/home/momin/Documents/GitHub/ElegantRL/elegantrl/train/replay_buffer.py", line 67, in extend_buffer
    self.buf_other[self.next_id:next_idx] = other
RuntimeError: The expanded size of the tensor (3) must match the existing size (6) at non-singleton dimension 1.  Target sizes: [2000, 3].  Tensor sizes: [2000, 6]
```

It seems to me like some tensor/buffer is being concatenated in the wrong dimension - meaning, it's concatenated along the 1-dimension and turned into `shape: [2000, 6]` instead of along the 0-dimension with `shape: [4000, 3]`.

Happy to try to investigate the cause of this further if you all would like.

**Comment by supersglzc** [comment]
The codes under **examples** folder are updated. Feel free to try new Colab examples [here](https://github.com/AI4Finance-Foundation/ElegantRL/blob/master/tutorial_LunarLanderContinuous_v2.ipynb).
